# Generated by Django 4.0.1 on 2022-02-08 16:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('contents', models.CharField(max_length=500000000)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 16, 51, 41, 600126, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=500)),
            ],
        ),
    ]
